import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Salesmodulelayout from '../layouts/sidebarlayouts'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Micro App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Salesmodulelayout>{children}</Salesmodulelayout>
      </body>
    </html>
  );
}
